### ISSUE TITLE
Open channel & Open playlist

### ISSUE THREAD

**Issue by mapi68** [yuliskov/SmartTubeNext#1094]
"Open channel" is used instead of "Open playlist".

1) Open a channel;
2) Search for a playlist;
3) Click OK for a long time;
4) On the right you see menu;
5) First item is "Open channel" but the command open playslist.

From:
    <string name="open_channel">Open channel</string>
to:
    <string name="open_playlist">Open playlist</string>

**Comment by mapi68** [comment]
Did you understand the problem?

**Comment by costinmx** [comment]
Agree. Most likely this issue is linked with #1083 
Older playlists have a normal context menu with two functions: "Open playlist / Pin Unpin from sidebar"
Newer playlists context menu is wrong: "Open channel / Subscribe Unsubscribe" instead of the normal one described above.
I hope Yuri @yuliskov notice this

**Comment by costinmx** [comment]
Hope it helps @yuliskov 
Just noticed, this issue is easily identifiable: 
1. Open a channel with a rich 'Created playlists' section. Try "Sky News", and find the catalogue 'Created playlists'.
2. Scroll right cards, in the 'Created playlists' section. You will find two behaviours:
    - Up to some point, playlist cards will show the number of videos in mid right, and channel name in bottom left. 
       If you access the context menu on this playlist card, you got 'Open channel' and 'Subscribe', faulty options;
    - After some point, playlist cards will show only the number of videos in bottom left of the card.
       If you access the context menu on this playlist card, you got 'Open playlist' and 'Pin to sidebar', correct options;
For easy referencing, in my case, the boundry was exactly between "The G7 Summit" card and "Climate Diaries".

**Comment by costinmx** [comment]
This issue looks solved after v13.66. Everything is working fine now.
From my POV, this topic may be closed. Also #1083

**Comment by mapi68** [comment]
Ok, closed.
