### ISSUE TITLE
Add/Remove from recent playlist is confusing now

### ISSUE THREAD

**Issue by DTK21** [yuliskov/SmartTubeNext#1506]
So before the update, the option would have either "Add to 'Recent playlist'" or "Remove from 'Recent Playlist'" which let users know if videos were already added

But now, whether a video is in a recent playlist or not it will only have "Add/Remove from 'Recent playlist'" and you wouldn't know if that video was added or removed

**Comment by costinmx** [comment]
I'm guessing you are still confused about that, but the point remains.
'Add to <Recent playlist>' or 'Remove from <Recent playlist>' are missing in most circumstances after last update. This two context shortcuts were adaptable, where <Recent playlist> means the last playlist you ever added or substracted a clip. Keyword is 'Recent'. This shortcut inadvertedly also informed you about the status of your addition to playlist. Which was great, as an option, BTW. Gone now.

The other function (that remains) 'Add/Remove from playlist' is a single different function which brings up the entire playlist of your account.

**Comment by elle8che** [comment]
> So before the update, the option would have either "Add to 'Recent playlist'" or "Remove from 'Recent Playlist'" which let users know if videos were already added
> 
> But now, whether a video is in a recent playlist or not it will only have "Add/Remove from 'Recent playlist'" and you wouldn't know if that video was added or removed

I like this idea. I wouldn't mind seeing this (again?). My context menu has "Add/Remove from _whateverrecentlist_" as well as "Unsubscribed from channel" -- I can't tell if the video is already in the _whateverrecentlist_ playlist or not by this context (and BTW, it is), but I can see just by the menu item name that I **am** subscribed to the channel.  

Honestly, it wouldn't be a huge deal (and it's not major, but...) but it would definitely save clicks, which means remote battery usage (every click counts), wear and tear on my remote, and additional usage of the device (Fire Stick, for me). Currently, if I right click to the menu (1), click down 1 to the "Add/Remove from _whateverrecentlist_" item, then click on it to add the video, I will get a notice of "Removed from _whateverrecentlist_" because it was already on the list. FYI, I'm doing this from the search results page, where I often use the context menu to save to a playlist from this screen. Other screens may vary. I sometimes forget if I've added a particular video to a particular playlist or not, so I double-check. Having the menu read either "Add from _whateverrecentlist_" or "Remove from _whateverrecentlist_", accordingly, would save up to 4 clicks each time and would still only require one menu item space. 

Just spitballing.

**Comment by DTK21** [comment]
Yeah I just reverted back a few updates, it's there and works as it did before but I don't want to rely on a notification at the bottom of the screen say "added or remove" which for me it doesn't even do on the latest update. Especially if it makes a video end up removed then added back in but at the back of the watch list

As for the subscribe/unsubscribe, that should work tye same way as the "add to recent playlist" and "remove from recent playlist" and not combined as "Subscribe/Unsubscribe to channel" because that gets hard to tell and Yitube being bad enough with the whole "ring the bell" finding that one of multiple channels you have that was accidentally removed doesn't help

**Comment by costinmx** [comment]
In my case (Google TV and Android TV) this option "Add or Remove from recent pl." was not present anymore, at all, in 14.82. Just dissapeared from context menus, even if is active in Options. 
For me it's a regression, so I also rolled back to a previous working version. Wondering what's the point of having and then removing useful features. Rolling back versions is only a temporary fix when dealing with YT.

**Comment by DTK21** [comment]
So there's been an update, and though I still don't get a notification that a video got added to the most recent playlist, if a video is added already it will ask to confirm removal. This is ok but the old way just seems more quick, less tedious,  and more cofirming when you see "remove from recent playlist" compared to "Add/Remove from recent playlist"
But I will say though, the confirming thing can help for "Subscribe/Unsubcribe to channel" since testing that out I don't even know if I did unless I view a video then check that way

I wouldn't remove it altogether but make it optional because my android tv box remote can press multiple buttons to hold select then scroll down one to not accidentally remove a video. Meanwhile my android tv remote can't multi-select so it's good for that device

If it ain't broke don't fix it but if there's something new, add it as a feature too

**Comment by costinmx** [comment]
I am really really sad to hear about this. Looks like were stuck to older versions. That's it?
For me it's still missing this feature at all. And it really hurts because adding and removing clips to specific playlists used to be so easy, with just 2 clicks. Now it's always 4-5 clicks away for every clip.
@yuliskov , please, cannot bring back the usual functional "Add/Remove to recent" playlist? The way it was?
It is really hard to understand why is this changed. 
Regards.
![Screenshot_20220515-202810](https://user-images.githubusercontent.com/74626232/168486644-26fda109-76f6-44fe-be8b-a6813209deff.png)
![Screenshot_20220515-202841](https://user-images.githubusercontent.com/74626232/168486649-b53e2dff-815d-434f-8001-e1b189792515.png)

**Comment by costinmx** [comment]
Update: While in some cases the menu does not appear, in some works. Cannot figure out why.
When is does, works in the wicked way described in posts above. Confusing, erratic. Sometimes asks for confirmation (silly), sometimes dont. Sometimes Adds the video again and again, and it does not switch to "Remove".

This used to be a perfect working feature/context menu, also present in original YT app. Cannot understand why it had to change....

**Comment by costinmx** [comment]
This issue seems to be fixed in 14.86. 
But here it is another big issue: In Playlists section, Watch Later is gone to the bottom of the list? 
I'm really starting to lose hope here..........

**Comment by yuliskov** [comment]
Position of the Watch later will be restored on the next beta release.
Sorry for the inconveniences.

Regards, Yuriy

**Comment by costinmx** [comment]
Many greetings, Yuri... 
I think this topic may be closed, if the author agrees

**Comment by costinmx** [comment]
Could you also please include displaying "Sort playlist" as an option in context menu settings? It would be very useful. Thank you. 
Regards.

> Position of the Watch later will be restored on the next beta release. Sorry for the inconveniences. Regards, Yuriy
> […](#)
> On Wed, May 18, 2022, 00:00 costinmx ***@***.***> wrote: This issue seems to be fixed in 14.86. But here it is another big issue: In Playlists section, Watch Later is gone to the bottom of the list

**Comment by yuliskov** [comment]
Sure, thx

Regards, Yuriy

**Comment by DTK21** [comment]
Yes indeed the situation has been resolved, and thanks goes towards the teams for the testing and tweaking as well as providing continued support. I will close this out, but I'll end off with this. 
I still feel that change has a place as long as the indicator is clear and can help with users that have single input remotes, as long as there is an option to revert back in forth for both kinds of QoL. Also to repeat my earlier comment that the confirming removal could be useful for when unsubscribing to a channel as a safety measure. 
Other than that thanks for the understandings.

**Comment by Jamie-Landeg-Jones** [comment]
> Position of the Watch later will be restored on the next beta release. Sorry for the inconveniences. Regards, Yuriy

Thanks for doing this. I was really gutted to see it disappear, so a big thumbs up for listening !
