### ISSUE TITLE
Is the turn off screen button safe for OLEDs for burn-in?

### ISSUE THREAD

**Issue by Kristijan1001** [yuliskov/SmartTubeNext#1903]
Is it safe cause from the looks screen just goes black and doesn't turn off ?

**Comment by ClementNerma** [comment]
Burn-in essentially comes from the pixels always displaying the same color while on. So for instance if you always watch the same TV channels the logo may cause burn in. Other than that on modern OLED TVs this isn't really a problem as there are many mechanisms to prevent it.

Turning the pixels black mean they aren't being used, so this can't trigger burn-in. Quite the opposite in fact, as this will preserve the pixels instead of using them. It will probably not make a difference but it will certainly not harm your TV ;)

**Comment by Kristijan1001** [comment]
Thanks
