### ISSUE TITLE
Fix long-press menu

### ISSUE THREAD

**Issue by Soitora** [yuliskov/SmartTubeNext#216]
Right now from what it looks like (on Chromecast w/ Google TV) to add/remove a video to a playlist you need to hold down the main action button for a little while and then release. It would be better if the playlist menu automatically appeared after enough time has passed instead of having to guess if you've long pressed long enough.

**Comment by leledumbo** [comment]
Better if the menu can be triggered through menu button as well (long press can feel too long) and "add to watch later" is a direct option, just like in the original Youtube app and previous SmartYoutubeTV app.

**Comment by jdahdah** [comment]
Looks like this has been added! It's no longer necessary to release the ok button for the menu to pop up.

I would still love it if "Watch Later" could be added as a separate item in the context menu (1st position), so that I don't have to select "Add to playlist" and then choose the watchlist each time. It's the feature I use most.

**Comment by Soitora** [comment]
Fixed, so I'll close it!
