### ISSUE TITLE
Link with TV code

### ISSUE THREAD

**Issue by dotdotcannon** [yuliskov/SmartTubeNext#232]
Where's the 'Link with TV code' option?

**Comment by zhq111** [comment]
This can be

**Comment by WolfganP** [comment]
> Where's the 'Link with TV code' option?

Not in front of the TV right now, but I recall I linked thru Settings->Account

**Comment by zhq111** [comment]
This can be solved by logging in to your account, but it doesn't seem to be possible to screen your phone on your TV.

**Comment by Xandrez192** [comment]
Agreed, this is a feature from Smart YouTube for TV I would very much like to see, if it is possible to implement. My main use case for YouTube on my television is using the YouTube app on my phone as a remote (actually Vanced, because both worked with it) along with other people connected to the app, so multiple people can add videos to the queue without having to exit the video on the television and search there.

**Comment by foreveryoungforty** [comment]
Indeed, also for me the feature (which worked great on Smart YTV) I am really looking forward to.

**Comment by finnzz** [comment]
I'm hooing to see this added to SmartTubeNext as well

**Comment by nikitsi-a** [comment]
We really need this! :)

**Comment by sciencebug** [comment]
if it already worked in the previous app, whats the problem with porting it over?

**Comment by foreveryoungforty** [comment]
@dotdotcannon function made available in new version 10.75 - please close this issue - thanks.

**Comment by dotdotcannon** [comment]
Thanks!!!

**Comment by menachg** [comment]
I vote to reopen issue.
Was working a week ago but i tried re-linking and it fails with error message "error while adding the screen"
Using vanced v15.33.34
Smartube is fully updated on chromecast with androidTV
 i tried restarting both phone and tv but didnt help
