### ISSUE TITLE
Exit from playing mode to main menu requires to press back button twice

### ISSUE THREAD

**Issue by TeHashX** [yuliskov/SmartTubeNext#257]
Like title says: When I watch a video, I press "return" buton and a black screen with "Loading" message shows up, I have to press again "return" to exit to main menu, anyone else has same issue?
v10.54 installed on Chromecast with Google TV

**Comment by foreveryoungforty** [comment]
On my Sony 4K android tv,  playing a video, the stop or return/back-button on the remote stop the video and returns to screen where you started the video, so that's perfect.
To fully close the app, 2 times back, but that's nomal to avoid to exit the app too quicky, and the way fx explorer and mx player also work.

**Comment by TeHashX** [comment]
No, I want to return to screen where I started the video but I have to press the button twice.

**Comment by foreveryoungforty** [comment]
Strange, with me here I only have to press once

**Comment by realrobd** [comment]
Same here. 
Watching video > press back (get "Loading..." screen) > press again for video list.

**Comment by beyond1207** [comment]
I am also having the same issue. I press the back button while playing a video and a black loading screen shows up and doesn't go away until i press back once more. I am using a FireTV 4k stick.
