### ISSUE TITLE
[Feature Request] Show always-on-screen clock while playing video

### ISSUE THREAD

**Issue by PopeyeTheSai10r** [yuliskov/SmartTubeNext#2749]
It seems like the always-on-screen clock is present while browsing the app.
When video start playing the clock is tucked away with the video player settings.

It would good if we could a True always-on Clock that stay in the chosen position while browsing and while playing video.

**Comment by thebudman420** [comment]
Settings, Video player, misc, always show onscreen clock. This is what you want.

This is separate from settings, general, misc show always on screen clock. That is for the interface and the other setting is for the video.

This makes me wonder if the setting should be moved to the interface section of settings to remove confusion.

I use show always on screen clock on just the interface myself.

I don't use it on the video player because then the clock covers part of the video all the time.

However showing the clock when you bring up the player UI is completely fine then you can bring up the UI that shows other information like time and duration of the video and all your other buttons with the clock somewhere such as the top corner.

Otherwise if I'm in the middle of a video i just press the mic button on my remote and ask what time is it.

**Comment by thebudman420** [comment]
I will add that maybe the always show on screen clock in settings, video, misc should be renamed always show clock over video.

And the other setting should be moved from settings, general, misc to settings,. interface, misc because this always shows on the main interface except when searching.

Can also be renamed to always show clock over interface. Or always show clock on interface.

Or Always show clock on UI

Always show cock over UI.

Optional names suggestions.

**Comment by PopeyeTheSai10r** [comment]
> Settings, Video player, misc, always show onscreen clock. This is what you want.

This worked.
