### ISSUE TITLE
[Bug] Cannot watch age restricted videos

### ISSUE THREAD

**Issue by TooSuccessful** [yuliskov/SmartTubeNext#415]
I always get a black screen when I try to watch age restricted YouTube Videos. Even if I am logged in to my account. In the web browser it works without problems.

By the way, thank you for making this great app.

**Comment by TooSuccessful** [comment]
Works after verifying my age with my driver license. (https://support.google.com/youtube/answer/3159776?hl=en)

**Comment by Fieel** [comment]
I am having the same problem. My account age is verified. This only happens while using smarttube in my tv

**Comment by DraconicNEO** [comment]
Why not use the same method NewPipe uses to get the videos, age restrictions there are completely bypassed.

**Comment by Baegus** [comment]
It's probably because you use a "Brand Account" (not your actual Google/Gmail account). Brand accounts do not support adding a birth date, so when you link them to external devices, age restrictions kick in. There seems to be no way to use a Brand account with SmartTubeNext to play age-restricted videos. The solution would be to bypass age restriction entirely (#733).
