### ISSUE TITLE
Picture in picture

### ISSUE THREAD

**Issue by Ed254** [yuliskov/SmartTubeNext#457]
Hello, I've been using this app for a while now, however, I cannot get picture in picture to work. When I select only audio, background playback works, but selecting picture in picture does nothing.

**Comment by linuxstv** [comment]
Mine is working fine.

**Comment by finnzz** [comment]
If something is not working, list your system information
SmartTubeNext Version
OS version
Streaming device model

**Comment by Ed254** [comment]
Sorry, I'm relatively new to this, thank you for guiding me.
SmartTube version 10.96
OS android 9
TV is Hisense A72

**Comment by finnzz** [comment]
I don't have a solution for you but your specs are a good starting point :)

Does PIP work in any other app, for example Plex?  I'm asking just in case Hisense has disabled it in their build of AndroidTV

**Comment by Ed254** [comment]
I'm actually a noob on matters TV, I just use the smarttubenext app, nothing else installed.

**Comment by finnzz** [comment]
> I'm actually a noob on matters TV, I just use the smarttubenext app, nothing else installed.

Plex is the only app off the top of my head on AndroidTV that has a PIP option (I'm sure there are others). You can install Plex from the Google Play Store quick and easy.  When you play one of the advertisement supported TV shows or movies you will see the PIP icon on the bottom right corner of the player menu. 

I say this because the first thing I would check is to see if PIP works at all on your build of AndroidTV or if the issue is isolated to SmartTubeNext.

I can say that SmartTubeNext PIP works on FireTV and MiBoxS, so it's not like it doesn't work at all.

**Comment by Ed254** [comment]
Okay, did exactly as you said, no PIP icon. Oh well, too bad for this TV but I guess I'll just do without. Thank you so much for your patience.

**Comment by finnzz** [comment]
I was trying to find a Plex screenshot that shows the PIP icon on the player.  This is an older version of the player menu, but you can see the highlighted PIP icon.  That is now in the bottom right corner next to the 3 dots (menu)
https://external-preview.redd.it/JEVvzsLTYBUUxwrgEyLkfbdtD72DB6iF3Rz3MDr8uBQ.jpg?width=640&crop=smart&auto=webp&s=e6033d39339c5997f6849ebc8288ac6d8985176b

It's possible that Plex detects if PIP is enabled and hides the icon if it's not.  

Check the AndroidTV settings menu on your TV, maybe if you are lucky there will be an option to enable/disable picture-in-picture.

**Comment by Ed254** [comment]
Thank you so much. PIP is not really a must have for me but it'd be awesome to have it. I'll see what I can do in the future. Thanks again.
