### ISSUE TITLE
Casting stopped working

### ISSUE THREAD

**Issue by flappy81** [yuliskov/SmartTubeNext#462]
After the last few updates casting from Vanced at least, has stopped working. Connecting via code does nothing.

**Comment by foreveryoungforty** [comment]
Strange, version 10.92 works perfect here with that combination...

**Comment by flappy81** [comment]
Thanks for responding. That did the trick. Strange.

**Comment by mmortal03** [comment]
> Strange, version 10.92 works perfect here with that combination... maybe try complete uninstall and reinstall of smarttube.

Where did you get 10.92? The latest I see is 10.84: https://github.com/yuliskov/SmartTubeNext/releases

**Comment by foreveryoungforty** [comment]
As with all apps , there is an automatic update or check for update (see about), so just update, we are already on 10.96.

**Comment by mmortal03** [comment]
> As with all apps , there is an automatic update or check for update (see about), so just update, we are already on 10.96.

Thanks, that makes total sense. But the reason I've been monitoring the release versions on GitHub is because I don't want to permanently switch over to SmartTubeNext on my FireTV Stick until the functionality that I use daily in SmartYouTubeTV has been implemented. Specifically, the following casting feature: https://github.com/yuliskov/SmartTubeNext/issues/403 
I don't believe there's a way to keep them both installed on a FireTV Stick and compare their casting functionality, because they will interfere with each other.

**Comment by foreveryoungforty** [comment]
On my Sony android tv both apps are installed next to each other, no problem, they work independently.

**Comment by mmortal03** [comment]
> On my Sony android tv both apps are installed next to each other, no problem, they work independently.

I'll test it to see. Not trying to hijack this issue report, but assuming DIAL casting or Google Cast casting (from a desktop/laptop, not a phone) is re-implemented in SmartTubeNext like it was in SmartYouTubeTV, how would the system know which YouTube app to cast it to if both were installed? How it's always worked with SmartYouTubeTV is that it superseded the official YouTube app if it was also installed.

**Comment by zouden** [comment]
>How it's always worked with SmartYouTubeTV was that it superseded the official YouTube app if it was also installed, and the cast would be directed to SmartYouTubeTV.

That's not how it worked on my Fire TV. I could cast to "Fire TV" (the official app) or "Youtube on TV" (smart youtube app).

As of a few weeks ago, casting to Smart youtube app (or SmartTubeNext) does not work. I've come here looking for a solution.

**Comment by mmortal03** [comment]
> > How it's always worked with SmartYouTubeTV was that it superseded the official YouTube app if it was also installed, and the cast would be directed to SmartYouTubeTV.
> 
> That's not how it worked on my Fire TV. I could cast to "Fire TV" (the official app) or "Youtube on TV" (smart youtube app).
> 
> As of a few weeks ago, casting to Smart youtube app (or SmartTubeNext) does not work. I've come here looking for a solution.

Interesting. Was it casting from your phone, or from the Chrome browser on a desktop, where you're saying that you could cast to either? I'm strictly speaking of casting from the Chrome browser on a desktop, in situations where neither the official app or SmartYouTubeTV were already open, and it would always default to SmartYouTubeTV. I only ever got one entry in the Chrome browser casting dropdown to choose from, so I couldn't pick. I think when the official app was already open, it would cast to it, and possibly in situations where the Fire TV Stick was sleeping, but it's been a while since I tested this. Actually, a few weeks ago I uninstalled the official app, so I'd have to re-install it to test.

Anyway, I think the OP is talking about casting with a code, which is a separate issue from what I'm describing in my issue report: https://github.com/yuliskov/SmartTubeNext/issues/403

**Comment by zouden** [comment]
I was casting from my phone. But actually I just now un-paired my phone from the Smart youtube app and re-casted to it, and now there's only one cast target ("Fire TV") in my youtube app. Previously I had two targets. So I think you're right that it supersedes the official app. Presumably whichever app was last opened is the one that gets the cast signal.
