### ISSUE TITLE
[Feature Req.] Player icon labels

### ISSUE THREAD

**Issue by kuafor41** [yuliskov/SmartTubeNext#485]
Hi Yuri,
Could you please so kind and add label texts to the player icons instead current style ? I mean just a simple text below of the icon about what the icon is stand for (it can change when you press and show what the current status of playlist playing status kind of icons).
Thanks in advance.

**Comment by foreveryoungforty** [comment]
Hello, I get your point but I have some mixed feelings about it.
I wonder what is your opinion about these arguments why I think that way.

1) the player UI is already "crowded", adding texts will possibly overload it ?
2) most label texts will be longer than there is place for it, so there will be dots or it will be cut off
3) most icons are commonly used and known in many players and remote controls (for instance MX player use also icons without texts)
4) once you push on icons, it explains itself with extra menu's/options or confirming text-notifications
5) I find your suggestion most useful for the 4th icon in the 1st row, as it has 5 possible options, but the explanatory texts are longer than 1 word in most languages (so not simple to catch the meaning in 1 simple word), so that will cause my point 1 and 2.
6) Once you are familiar with the app and use, to me the current UI works is clear to me.
Best, Rik

**Comment by kuafor41** [comment]
> Hello, I get your point but I have some mixed feelings about it.
> I wonder what is your opinion about these arguments why I think that way.
> 
> 1. the player UI is already "crowded", adding texts will possibly overload it ?
> 2. most label texts will be longer than there is place for it, so there will be dots or it will be cut off
> 3. most icons are commonly used and known in many players and remote controls (for instance MX player uses also icons without texts)
> 4. once you push on icons, it explains itself with extra menu's/options or confirming text-notifications
> 5. I find your suggestion most useful for the 4th icon in the 1st row, as it has 5 possible options, but the explanatory texts are longer than 1 word in most languages (so not simple to catch the meaning in 1 simple word), so that will cause my point 1 and 2.
> 6. Once you are familiar with the app and use, to me the current UI works fine and is clear to me.
>    Best, Rik

Hi Rik,

I agree, the actual reason behind of this request is; i am losting the notification thing that you explained it with your 4th. item between updates _(actually still not figure out what is causing this)_ and only solution is swipe all data of the application and then i should re-modify all the options. You're correct on your some items especially 5th. BUT if this is a case for some other users it is really annoying. I am using this app with no icon notification most of the time maybe there can be another solution or this can trackable under **bug** category by the developer for solution then i am ok with old style. I will finally memorize what the 4th icon statuses are and this will be my solution. :S 

Regards

**Comment by foreveryoungforty** [comment]
I think that with the latest updates, the different icons were improved a lot by Yuriy, especially the 2 pause-functions regarding 4th icon, one with the pauze in the arrows, and one with the lines for playlist, that explains a lot.  I always leave my notifications for SmartTube on in my android tv settings. I think if text would be added to tbe icons, it would be best if there is an optional setting in the player settings to put the text on or off, according to the preference of the user himself.
Thanks for your reply.

**Comment by finnzz** [comment]
I agree that text for the player icons makes things too crowded.  I prefer to keep what space is there now for future icons/features.
