### ISSUE TITLE
Channel sections disappeared

### ISSUE THREAD

**Issue by stvrly** [yuliskov/SmartTubeNext#490]
App updated to 10.105 this evening. After this, the sections in my channel subscriptions disappeared. Each channel is now just one giant grid.

Running on Nvidia Shield TV Pro, software version 8.2.2 (latest).

**Comment by stvrly** [comment]
More information. I reverted to 10.84. Now, when I select a channel from the channel list, nothing appears. If I press and hold the center button on the remote to open the context menu, I see two options: "Open channel uploads" and "Unsubscribe from channel." If I select "Open channel uploads," I see the same upload grid that I noticed with 10.105.

I'm no expert on the intricacies of YouTube, but this has me wondering if YouTube made some changes? I explored a bit, and I think the channel list page that I'm accustomed to seeing in SmartTubeNext is the "featured" page, such as `youtube.com/c/NASA/featured` and `youtube.com/c/WorldScienceFestival/featured`.

**Comment by foreveryoungforty** [comment]
On Telegram the 10.105 release mentions "Channel section fix (not ideal sry)", so it's work in progress, will be optimized.

**Comment by DiscoFever78** [comment]
+1 ...Having same issues as OP.

**Comment by stvrly** [comment]
> On Telegram the 10.105 release mentions "Channel section fix (not ideal sry)", so it's work in progress, will be optimized.

Thanks for the update. Not a Telegram user here...

**Comment by costinmx** [comment]
> App updated to 10.105 this evening. After this, the sections in my channel subscriptions disappeared. Each channel is now just one giant grid.
> 
But it's fine...
Short press on subscription channel in this menu brings the "Uploads" section, not "a giant grid". This is exactly how it's on Youtube app. IMHO, it's ok. This Channels menu section is derived from YT Subscriptions, so at first access, you may instantly want to see newest videos, cronologically. It makes sense. Pitty we still don't have a left side menu with channels for that, just like in original YT. 
It's also easy to access the full channel categories here when needed, you just have to long press the Channel in this list and select "Open channel". It's the first option, so it's a long press followed by a short one.  Quite easy.

P.S. The old full channel access was flawed because Channel categories are yet not sorted in SmartTubeNext like in YT. So very often you struggle to find Uploads.

**Comment by stvrly** [comment]
> It's also easy to access the full channel categories here when needed, you just have to long press the Channel in this list and select "Open channel".
Hey @costinmx, thanks for that tip, it's exactly what I was looking for. Not sure why I didn't think of that myself, heh. Might be nice to have a toggle in the UI to change the behavior to show only uploads or all sections on short click. But I'm sure @yuliskov has other priorities, so I'll close this issue.
