### ISSUE TITLE
Ads not being blocked as of a few hours ago 

### ISSUE THREAD

**Issue by Temujin64** [yuliskov/SmartTubeNext#852]
Tried rebooting both the app and my Nvidia Shield. I also tried signing out and back in again. I turned the ad blocking option off and on again. Lastly, I uninstalled and reinstalled the app.

None of these stopped ads from appearing before certain videos.

**Comment by finnzz** [comment]
Are you talking about embedded video ads (blocked by SponsorBlock) or YouTube ads (shouldn't be possible to even play these)?

If you are talking about in video ads handled by SponsorBlock, is there color coding in the video bar indicating a sponsored segment?

One thing to keep in mind with SponsorBlock is that this is a community powered (no AI / algorithm) feature and actually requires people to indicate where intros, sponsored segments, etc are in a video, so that others can skip through them automatically.  Some videos may not have any labeled ads because nobody has added them by hand yet to the sponsorblock database.

**Comment by Temujin64** [comment]
I was in the wrong GitHub project. The issue was with Smart YouTube TV. My apologies.
