### ISSUE TITLE
Can't load content

### ISSUE THREAD

**Issue by Wicked0ne** [yuliskov/SmartTubeNext#863]
I'm using version beta 12.45 on my FireTV stick 4k. When I opened the app today nothing loads, just a black screen that says "Can't load content. 1) check network connection. 2) Try to sign in to your account" with a sign in button. When I click the sign in button it brings me to a screen where it says "User Code is loading..." And has one button labeled "done". No user code is ever shown, I have let it sit for 5 mins.

I have checked my internet connection and everything else works. I've tried closing and reopening the app several times. I have also cleared the apps cache. Nothing has fixed this issue.

**Comment by Rin-Rem** [comment]
Same issue, yesterday was very slow. But now I cant even load anything at all. Not even a user code to try and re log back in. Did Google fuck something up again?

**Comment by Wicked0ne** [comment]
After work digging around I discovered that my FireTV stick was unable to access ANY YouTube.com domain. After rebooting the FireTV stick SmartTubeNext now works properly. I have no idea how or why the FireTV stick blocked/was unable to access any YouTube domain. I feel like an idiot for not rebooting the FireTV stick before posting here.

@Rin-Rem See if you can access YouTube.com another way(diff YouTube client, browser, downloader, etc etc). If it still doesn't work, try a reboot. If that fixes it I'll close out this issue.

**Comment by Rin-Rem** [comment]
Did a little extra testing on my end yesterday, turns out YouTube's domain was being blocked over my network. Don't know how it happened, but got into the gateway and just straight up whitelisted. Didn't work at first. But changed what network my fire stick was connected to and restarted. It is now working. So I was sorta dumb and should of just looked at that route first. But lesson learned. But thank you for the response :)

**Comment by Wicked0ne** [comment]
@Rin-Rem Huh, so weird that both out FireTV sticks(or firewalls) blocked YouTube.com at the same time. Good to hear it's working. I'll close this out.
