### ISSUE TITLE
Many Breaks For Buffering

### ISSUE THREAD

**Issue by Grauen** [yuliskov/SmartTubeNext#878]
Again - there are lots of breaks for buffering while watching 1080p videos. (vp9 4.46 MBit) 

Watching 4k videos with a firetv stick is impossible.

Buffer setting is set to High.

**Comment by ACR-Jeff** [comment]
Just a few ideas since this happened to me as well. I had this issue as well and it was a result of my ethernet hubs and etc hardware on my network only allowing 100mbps rather than 1000mbps. This results in slower ethernet. Also could be a possibility of your wifi modem/router settings as well as distance from your hardware.

**Comment by Grauen** [comment]
No. This was caused by YouTube I guess. It's working with 1080p now but 4k is still impossible to watch.
