### ISSUE TITLE
[Bug] The FPS on Presets are not respected anymore in recent versions.

### ISSUE THREAD

**Issue by onolox** [yuliskov/SmartTubeNext#910]
The bug is that the fps is not respected anymore. 
I use the preset with 2160p 30fps vp9 hdr. All the streams that was automatically selected use 30fps max, even if it makes the resolution fall to 720p/30fps. Now it plays 60fps regardless of the preset. The preset of 30fps is completely ignored.

The intented behavior is to STN to select the best resolution that have 30fps max. 
Because my x96max+ only plays well in increased speed with maximum os 30fps.
The last working version is 11.98.

**Comment by HobbyCoderSWE** [comment]
I have the same problem...
My TV does not work well with 60fps. My wish is that there would be an option to select maximum fps allowed filter or something alike. Could also add format filter there as well. That way we only see/play what the TV can handle the best.
Thanks for listening.
But as onolox said. If we choose a preset that has 30fps it should NEVER choose anything above that.

**Comment by shield72** [comment]
It's been a month now since this problem has been reported, but despite several updates, this problem still exists. And boy, it's not a small one.  

For several weeks now the first thing I normally (!) do after starting a video is calling up the video quality settings in order to set those 60 fps, which causes severe stuttering on my device, back to a smooth 30 fps. This happens with every 30 fps preset, regardless of its codec and resolution.

@ yuliskov: Please, can you fix this issue?

**Comment by FabioM3** [comment]
I'm still using the old 11.98 beta, but this version is becoming problematic, I need to go up and down to make the sections poroperly update, the search doesn't work, the videos takes a while to start, buffering problems...

The latest versions doesn't have any problems, even the lag that I'm having is gone, but I can't update because the newer app don't respect the 30fps cap of the preset.
@yuliskov I think this is a small fix?

**Comment by yuliskov** [comment]
Sure.

Post there name of your present (1080 30fps avc) and the sample video where
you spotted the bug.

Regards, Yuriy

**Comment by yuliskov** [comment]
Thx. I'll fix as soon as possible.

Regards, Yuriy

**Comment by FabioM3** [comment]
Well a month+ have past and this majos bug still exists...

**Comment by FabioM3** [comment]
@yuliskov any fix for this or I can loose all hope?

**Comment by yuliskov** [comment]
@FabioM3 actually, I've implemented 'strict fps match' long time ago but not enabled it. Don't know why. Maybe, I don't like the result or something else. Anyway, in the next beta I'll enable it by default. Let's see how it goes.

**Comment by yuliskov** [comment]
beta 13.85 with the fix is released

**Comment by onolox** [comment]
Heeeeeeeeyyyyyy finaly the nighmare is over! eheheheheh
Thanks yuliskov.
